### ISSUE TITLE
Rename to python-sass

### ISSUE THREAD

**Issue by bashmish** [pistolero/python-scss#1]
Original library name is SASS that has two dialects of SASS and SCSS.
Why not to name your bindings in accordance with original name?

**Comment by pistolero** [comment]
Actually `libsaas` supports only SCSS dialect, so the project name is right. But module name (`sass`) is probably wrong then.

**Comment by bashmish** [comment]
@pistolero aren't they going to support SASS dialect in future releases?

**Comment by pistolero** [comment]
I'm not sure

**Comment by pistolero** [comment]
https://github.com/hcatlin/libsass/issues/16
