### ISSUE TITLE
Supply Windows binaries

### ISSUE THREAD

**Issue by cool-RR** [pistolero/python-scss#17]
It would be nice if you would supply binaries of Sass for Windows. (I personally need for Python 3.3 64bit, but a variety would be good.)

**Comment by pistolero** [comment]
Sorry, I don't have a Windows box near me.

**Comment by cool-RR** [comment]
I personally no longer have a need for this, so feel free to close. But, if you want to serve Windows users better, you can set up a Windows VM with scripts to automatically build your project, and then use that whenever making a new release. It's quite an effort though, so I'd understand if you'd opt to not do it.

**Comment by pistolero** [comment]
I'm too lazy for this :)
