### ISSUE TITLE
Cython should be listed as a dependency

### ISSUE THREAD

**Issue by cuerty** [pistolero/python-scss#19]
Simply running "pip install sass" on a clean virtualenv fails with the following error:

```
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I. -Ilibsass -I/usr/include/python2.7 -c sass.c -o build/temp.linux-x86_64-2.7/sass.o

gcc: error: sass.c: No such file or directory

gcc: fatal error: no input files

compilation terminated.

error: command 'gcc' failed with exit status 4
```

After manually installing Cython in that virtualenv, the build succeeded. I'm doing this on Ubuntu 12.04 with Python 2.7.

**Comment by pistolero** [comment]
Fixed in 2.2. Now `pip install sass` should work without `cython`.
