### ISSUE TITLE
Packages on PyPI

### ISSUE THREAD

**Issue by ronnix** [pistolero/python-scss#6]
I'd like to be able to do a `pip install sass` on Mac OS X.

Currently, there is only a binary package for Linux available on PyPI at http://pypi.python.org/pypi/sass/1.0

Could you also upload a source package?

**Comment by pistolero** [comment]
Try now

**Comment by ronnix** [comment]
Thanks!

Note that I had to compile libsass this way so that it finds the headers:

```
$ ./configure --includedir=/usr/local/include/libsass
$ make
$ make install install-data
```

(The default is to install `sass_interface.h` directly in /usr/local/include, so the `#include` in `sass.c` would fail.)

**Comment by pistolero** [comment]
Ok. If you are can fix problem with inclustion of sass_interface, do it please, and send me pull request.
