### ISSUE TITLE
Update libsass

### ISSUE THREAD

**Issue by tgecho** [pistolero/python-scss#8]
I was trying to update libsass in a local checkout of this repo, but I can't seem to get it to build properly. Everything I do seems to end with `no such file or directory: 'sass.c'`

It seem like I'm hitting the same issue @ronnix had in #6, but I'm not having any luck with his workaround. Do you have any instructions/tips?

**Comment by QuLogic** [comment]
It would be better if you explained "Everything you did".

**Comment by tgecho** [comment]
Good point... that's what I get for hurriedly summarizing on my way out of the door...

I tried just `pip install -e` on the directory itself. I also tried `make`, `make all`.

Going back, I did just figure out that I needed to manually `pip install cython` followed by `make all`. I was sure I'd seen an "installing cython" line somewhere in the output the first time I'd tried it, but I guess I was imagining things. Sorry, new to the cython stuff.
